### PR TITLE
Added system diagram

### PR DESCRIPTION
**Pull request by itzg**
# Resolves

https://jira.rax.io/browse/CERES-354

# How

Added a system diagram to help visualize and group the services implemented. It is inlined into the top of the DESIGN.md document.

### CODE REVIEW

**Review by jjbuchan — APPROVED** [review]
There's some conflicts that need fixed and I'm not sure how downsample processor interacts with query service but that's likely because I don't understand ceres enough.

But I like the diagram and the colors!

**Comment by itzg** [comment]
Yeah, I'm not sure what happened git-wise with the skaffold file. My local workspace update got confused by that too.

I was debating adding descriptions to the various lines, which would have helped answer your question about downsample processor -> query service ...but opted to avoid the noise in this particular diagram since it was already noisy.

For now, the short answer is that downsample processor does it's work by querying for a downsample-time-slot's worth of data (such as the previous hour's of a data for a given tenant+metric+tags) and downsamples those values by granularity.

**Review by jjbuchan — DISMISSED** [review]

**Review by jjbuchan — APPROVED** [review]
> Enabled white background on diagram 

It was transparent before?

**Comment by itzg** [comment]
> > Enabled white background on diagram
> 
> It was transparent before?

Yeah, I forget that's the default in draw.io until I'll see it in something like the IntelliJ image viewer

**Review by jjbuchan — APPROVED** [review]
Nice addition.  Thanks.

**Review by GeorgeJahad — APPROVED** [review]

**Pull request merged**
