### PR TITLE
fixup the cloudbuild yaml files and pom.xml

### PR DESCRIPTION
**Pull request by shawnashlee**

### CODE REVIEW

**Comment by thebwt** [comment]
cloud build go 💥

**Comment by thebwt** [comment]
Okay, let's get some dev help next week figuring out what's going on with spawning these containers

**Review by rohitsngh27 — DISMISSED** [review]

**Review by thebwt — CHANGES_REQUESTED** [review]
This is failing, we need to investigate before merge.

**Comment by thebwt** [comment]
brilliant!

**Review by rohitsngh27 — APPROVED** [review]

**Pull request merged**
